name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Navigate to Persona API
      run: cd Backend/persona-donator-node
    - name: SAM CLI Installation
      run: |
        git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
        mkdir ~/.linuxbrew/bin
        ln -s ../Homebrew/bin/brew ~/.linuxbrew/bin
        eval $(~/.linuxbrew/bin/brew shellenv)
        brew --version
        brew tap aws/tap
        brew install aws-sam-cli
        sam --version
    - name: Set AWS Credentials
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
        echo $AWS_ACCESS_KEY_ID
    # - name: run the AWS Deploy Command
    #   run: aws cloudformation deploy --template-file packaged-test.yaml --stack-name persona-donator-node-test
