name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use AWS SAM Actions
      uses: apex/actions/aws/sam@master
      secrets: 
      - AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      run: |
        sam package --template-file template-test.yaml --output-template-file packaged.yaml --s3-bucket aws-devday-hack-team7
        sam deploy --template-file packaged-test.yaml --stack-name persona-donator-node-test --capabilities CAPABILITY_IAM