name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://pahud/aws-sam-cli
    - name: SAM CLI Installation
      run: |
        sudo apt-get install python3.7
        python3.7 -m pip install aws-sam-cli
        sam --version
    - name: Set AWS Credentials
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
        echo $AWS_ACCESS_KEY_ID
    - name: Checkout code
      run: |
        git clone https://github.com/patvin80/awshackday2019.git
        git checkout enhancements/nodeimprovements
        cd Backend/persona-donator-node
        pwd
      
    # - name: run the AWS Deploy Command
    #   run: aws cloudformation deploy --template-file packaged-test.yaml --stack-name persona-donator-node-test
