name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v1
    # - name: Test the code
    #   run: |
    #     cd Backend/persona-donator-node/personadonator
    #     npm build
    #     npm test
    #     cd ../../../
    - name: Use AWS SAM Actions
      uses: apex/actions/aws/sam@master
      with:
        args: package --template-file Backend/persona-donator-node/template-test.yaml --output-template-file Backend/persona-donator-node/packaged-test.yaml --s3-bucket aws-devday-hack-team7
      env: 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
    - name: Publish to AWS Environment
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws cloudformation deploy --template-file /github/workspace/Backend/persona-donator-node/packaged-test.yaml --stack-name persona-donator-node-test --capabilities CAPABILITY_IAM
