name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set AWS Credentials
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        echo AWS_ACCESS_KEY_ID
        echo $AWS_ACCESS_KEY_ID
        cd Backend/persona-donator-node
        aws cloudformation deploy --template-file packaged-test.yaml --stack-name persona-donator-node-test --no-fail-on-empty-changeset --region us-east-1
