name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Action"
    - uses: actions/checkout@v1
    - name: "Use AWS SAM Actions"
      uses: docker://pahud/aws-sam-cli
      run: |
        pwd
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        sam --version
        sam package --template-file template-test.yaml --output-template-file packaged.yaml --s3-bucket aws-devday-hack-team7
        sam deploy --template-file packaged-test.yaml --stack-name persona-donator-node-test --capabilities CAPABILITY_IAM
      env: 
      - AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}