name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set AWS Credentials
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
    - name: Navigate to Persona API
      run: | 
        cd Backend/persona-donator-node
        aws cloudformation deploy --template-file packaged-test.yaml --stack-name persona-donator-node-test
