name: CI

on: [push]

jobs:
  build:
    
    steps:
    - uses: docker://pahud/aws-sam-cli
    - name: Navigate to Persona API
      run: cd Backend/persona-donator-node
    - name: SAM CLI Installation
      run: |
        sam --version
    - name: Set AWS Credentials
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
        echo $AWS_ACCESS_KEY_ID
    # - name: run the AWS Deploy Command
    #   run: aws cloudformation deploy --template-file packaged-test.yaml --stack-name persona-donator-node-test
